name: Build project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 12
      uses: actions/setup-node@v3
      with:
        node-version: 12
        cache: 'npm'
    - run: npm update -g npm && npm install -g pnpm@5
    - run: pnpm install
    - run: pnpm run build
    - run: pnpm run pkg -t node12-win --out-path dist main.js
  
  build-linux:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 12
        uses: actions/setup-node@v3
        with:
          node-version: 12
          cache: 'npm'
      - run: apt-get install libasound2-dev
      - run: npm install -g pnpm@5
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run pkg -t node12-linux --out-path dist main.js
